### ISSUE TITLE
The project file cannot be opened...There is a missing project subtype

### ISSUE THREAD

**Issue by jaredcnance** [ligershark/sidewafflev2#1]
When trying to create a "Template pack project template (SideWaffle)" I get the following error.

I am running VS Community 2017

![image](https://user-images.githubusercontent.com/13851721/29381073-aea1445e-828d-11e7-9011-fb05ec0bb3dd.png)
![image](https://user-images.githubusercontent.com/13851721/29381078-b3d91b04-828d-11e7-9b69-82577a0b78f2.png)

**Comment by sayedihashimi** [comment]
Do you have 2017 15.3 with Extensibility tools installed? I forgot to mention to install Extensibility tools, it may be the reason.

**Comment by jaredcnance** [comment]
Further investigation revealed I had to [install the VS SDK](https://docs.microsoft.com/en-us/visualstudio/extensibility/installing-the-visual-studio-sdk) and then [Extensibility Tools](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ExtensibilityTools)
