### ISSUE TITLE
Add support for vs4mac

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/sidewafflev2#20]
We should add support for vs4mac https://github.com/dotnet/templating/issues/1209#issuecomment-323148499

**Comment by tylerbhughes** [comment]
I'm glad to know that this is possible. I'll see about getting VS4Mac installed this weekend.

**Comment by sayedihashimi** [comment]
Great!

**Comment by tylerbhughes** [comment]
@sayedihashimi I just finished installing Visual Studio Community for Mac. I also went ahead and installed the AddinMaker extesnsion. I guess my first question is what will we be able to make this repo work with VS for Mac or do we need a different repo just for the Mac version?

**Comment by tylerbhughes** [comment]
**Update:**

I tried to open the solution in Visual Studio for Mac but I keep running into the error provided in the screenshot. When I go to create a new project I can see in the GUI that it is going to create the .sln and .csproj files so I know it is supposed to be able to recognize the solution file. I'm guessing there's just something in the .sln file that is only recognized by the version of VS for Windows. 

![screen shot 2017-09-11 at 10 55 59 pm](https://user-images.githubusercontent.com/2483249/30307543-72c56d68-9744-11e7-9952-acf5f323e217.png)

@sayedihashimi any suggestions? It'd be great if we could get this working within this project and could setup deploy scripts that will generate a VSIX and a MPACK file when we're ready to release a new version.

**Comment by tylerbhughes** [comment]
@mhutch I know you were on the original thread talking about this. Can you provide any input to my issue above?

**Comment by sayedihashimi** [comment]
@tylerbhughes SideWaffle depends on the VS Extensibility Projects, so it won't load in VSMac.

**Comment by tylerbhughes** [comment]
@sayedihashimi alright, should we create a new repo for the SideWaffle4Mac project? Since I'll have to start new to add this support.

**Comment by mhutch** [comment]
I'd probably suggest creating a SideWaffle.Creator.Mac in this repo so it's easy to share code between the two extensions (maybe factor out some shareable code from SideWaffle.Creator into a library).

**Comment by sayedihashimi** [comment]
No longer needed, Template Engine templates will automatically appear after being installed.
