### ISSUE TITLE
When creating a new project the temp pack project template is Generated !

### ISSUE THREAD

**Issue by mustafasaaed** [ligershark/sidewafflev2#21]
I created a aspnetcore projecte then added the side waffle temp pack project template  
and everything is working fine but the temp pack is generated with every project from that template.

So here is the Template project:
![image](https://user-images.githubusercontent.com/25353476/30751370-745ead60-9fb9-11e7-8ead-d1546a72a0a3.png)

and here is the Generated project directory:

![image](https://user-images.githubusercontent.com/25353476/30751495-c3d636d8-9fb9-11e7-83af-ebc512d8a750.png)

**Comment by sayedihashimi** [comment]
Hi @mustafasaaed the folder that contains the `.template.config` folder is the root of the sources. If you want it to only generate the `WebApp` folder then move the `.template.config` folder under `WebApp`.

**Comment by mustafasaaed** [comment]
Hi @sayedihashimi Thanks for your reply ! 
I tried the second solution and it worked. Thank You very much
