### ISSUE TITLE
SideWaffle Creator can’t handle an Azure Resource Group project template 

### ISSUE THREAD

**Issue by managedcoder** [ligershark/sidewafflev2#22]
SideWaffle Creator can’t handle an Azure Resource Group project template – It creates the VS extension but I get a “File Not Found” error when I use my VS extension in the experimental instance of VS and no project files show up.

**Comment by sayedihashimi** [comment]
This is usually related to primaryOutputs in `template.json` is that set correctly?

**Comment by managedcoder** [comment]
I think I have that right… you can see it below.  Something to note is the fact that the ARM project template does not have curly brackets in it.  That’s just the way it is from the VS .csproj file itself.  I actually tried it with and without curlys to no avail.  Is that lack of curlys problematic?

"guids": [
    "{81e4fff2-9d54-40c4-834e-49fab9a762b0}", // MobileBaseline
    "68d82a27-f8ea-4550-9ac7-766cc4ca164e",   // MobileBaseline.ARM
    "{3b3622a0-8322-4dcd-9e5c-8cc6e17e521f}", // MobileBaseline.Droid
    "{c28c757a-4ec0-4966-80bc-0e4bdf5d288c}", // MobileBaseline.iOS
    "{BB5B1143-727E-467E-BC95-AD70BCD555B8}", // MobileBaseline.UWP
    "{9854193d-8d38-4dbd-935e-658417ed920d}" // MobileBaselineService
  ],
  "primaryOutputs": [
    {
      "path": "MobileBaseline\\MobileBaseline.csproj"
    },
    {
      "path": "MobileBaseline.ARM\\MobileBaseline.ARM.csproj"
    },
    {
      "path": "Droid\\MobileBaseline.Droid.csproj"
    },
    {
      "path": "iOS\\MobileBaseline.iOS.csproj"
    },
    {
      "path": "UWP\\MobileBaseline.UWP.csproj"
    },
    {
      "path": "MobileBaselineService\\MobileBaselineService.csproj"
    }
  ]

**Comment by managedcoder** [comment]
You were correct!  I had primaryOutput set incorrectly.
