### ISSUE TITLE
#if statements are not being carried over to extension properly

### ISSUE THREAD

**Issue by managedcoder** [ligershark/sidewafflev2#23]
#if statements are not being carried over to extension properly.  If the conditional compilation symbol associated with #if statements are defined then the code in the #if block will be generated but not the associated #if statement.  If the conditional compilation symbol is not defined then then the #if and the code within the block don’t get generated by the VS extension (i.e. the whole block disappears).  I need these #if statement and the code within them to flow to generated project source code when vs extension is used.

**Comment by sayedihashimi** [comment]
What file types are you using here? Did you see https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax

**Comment by managedcoder** [comment]
Ah, I think I see what might be going on here.  The Template Engine is processing my conditional expression but I actually want them to be part of the generated source, not processed by the Template Engine.  How do I get that done?

-Russ

**Comment by managedcoder** [comment]
Ok, I have the solution to my problem now.  Turns out that you can add conditional directives to your code that tell the template engine to ignore blocks of code.  This is done in a comment statement appropriate for the source in question.  So, for my c# files, I surrounded the #if statements I wanted preserved like so:

//-:cnd:noEmit
#if CONDITION
    <your code here>
#endif
//+:cnd:noEmit

The -:cnd suspends processing and the +:cnd resumes it.  I could have surrounded the #if and #end statements individually if I needed the <your code here> to be processed (its unprocessed in my example because I sandwiched the entire #if statement with the suspend/resume directives).

See this link for details:
https://github.com/dotnet/templating/issues/1354#issuecomment-346186262
