### ISSUE TITLE
Can't Make a Template Pack

### ISSUE THREAD

**Issue by someRandomCoder7** [ligershark/sidewafflev2#29]
Whenever I try to make a Template Pack, VS 2017 throws an error that says "There is a missing project subtype.
Subtype: '{82b43b9b-a64c-4715-b499-d71e9ca2bd60}' is
unsupported by installation."

**Comment by sayedihashimi** [comment]
It sounds like you don't have the Visual Studio Extensibility components installed. That's required for creating templates.

**Comment by sayedihashimi** [comment]
@someRandomCoder7 here is what you need

![image](https://user-images.githubusercontent.com/1283154/37933496-6378999c-3119-11e8-8837-508a52cc8f5a.png)


FYI @madskristensen the docs at https://docs.microsoft.com/en-us/visualstudio/extensibility/installing-the-visual-studio-sdk do not provide enough info.

**Comment by someRandomCoder7** [comment]
I already have that.

**Comment by sayedihashimi** [comment]
In the new project dialog do you see an Extensibility section?

**Comment by someRandomCoder7** [comment]
Yes I do.  In there is the "C# Item Template", "C# Project Template", "VISX Project", and the "SideWaffle Template Pack".

**Comment by sayedihashimi** [comment]
Can you create a VSIX project there and see if you get any errors?

From the following it does look like an Extensibility project type guid
 - https://www.mztools.com/articles/2008/mz2008017.aspx
 - https://blogs.msdn.microsoft.com/dmx/2014/04/08/problem-solved-visual-studio-there-is-a-missing-project-subtype-subtype-82b43b9b-a64c-4715-b499-d71e9ca2bd60-is-unsupported-by-this-installation/

**Comment by someRandomCoder7** [comment]
Yes I can successfully make a VISX Project.  Although I am confused of the second part of your comment

**Comment by someRandomCoder7** [comment]
No, it actually has this ID: `VSIXProject4.f45707ff-0434-433f-bcaf-e4bf0c1c8f23`

**Comment by someRandomCoder7** [comment]
For some reason the Template Pack all of a suddenly works...
Thanks for the help.

**Comment by sayedihashimi** [comment]
@someRandomCoder7 sounds good, glad you got it working.
