### ISSUE TITLE
Remove Default Product ID and Publisher Name in Extension Manifest

### ISSUE THREAD

**Issue by shaggygi** [ligershark/sidewafflev2#3]
The name "Sayed Hashimi" is added in the template's vsixmanifest.

`<Identity Id="SideWaffle.Template.Sayed Hashimi.0f7f23b8-5889-4bd9-afc5-362f23135512" Version="1.0" Language="en-US" Publisher="Sayed Hashimi" />`

**Comment by sayedihashimi** [comment]
Thanks for the report I'll fix in a couple of days.

**Comment by shaggygi** [comment]
Looks good 👍   I also noticed the template project name is also now capitalized from other feedback.  Thanks!

**Comment by sayedihashimi** [comment]
I have released the fix to the vs marketplace. closing.
