### ISSUE TITLE
Unsupported (Visual studio unable to open template pack project) 

### ISSUE THREAD

**Issue by lhughey** [ligershark/sidewafflev2#37]
I'm receiving an error when attempting to add a new Template Pack Project Template after creating a new project.
Steps to reproduce.
1. Create a new console project.
2. right click project, Create Template
3. edit project file with 
4. Attempt to Add new Template Pack Template project (Error occurs here).

I'm using Visual Studio 15.7.5
The error Im receiving is below.
<img width="686" alt="screen shot 2018-07-29 at 2 51 41 pm" src="https://user-images.githubusercontent.com/3799892/43370370-7bd4231c-9343-11e8-9d46-c42bfdcbd8d1.png">

**Comment by sayedihashimi** [comment]
@lhughey can you share the .vsix that you are seeing this with?

**Comment by dschloesser91** [comment]
I had the same problem. Solution for me was to install Visual Studio-Extensionen-Development pack under "Tools -> Get Tools and Features", because the VSIX Project template is in this pack and needs to be installed.
