### ISSUE TITLE
Multi-project template is generating two .sln files

### ISSUE THREAD

**Issue by hallidev** [ligershark/sidewafflev2#38]
I've been following this YouTube video closely to build a multi-project template:
https://www.youtube.com/watch?v=g6az_N95dVM

My template solution (.NET Core) has the following structure:

/Company.WebApi.sln
/.template.config
/Company.WebApi.Model/Company.WebApi.Model.csproj
/Company.WebApi.Web/Company.WebApi.Web.csproj
/Company.WebApi.Service/Company.WebApi.Service.csproj
/Company.WebApi.Repository/Company.WebApi.Repository.csproj
/WebApiTemplatePack

When I actually use the template, I'd like to get the same structure minus the ".template.config" and "WebApiTemplatePack" folders.

Instead, I get the following:

/Company.WebApi.sln <--- this .sln file seems to have the correct projects in it
/Company.WebApi/Company.WebApi.sln <--- this .sln file has everything from my template project
/Company.WebApi/Company.WebApi.Model/Company.WebApi.Model.csproj
/Company.WebApi/Company.WebApi.Web/Company.WebApi.Web.csproj
/Company.WebApi/Company.WebApi.Service/Company.WebApi.Service.csproj
/Company.WebApi/Company.WebApi.Repository/Company.WebApi.Repository.csproj
/Company.WebApi/WebApiTemplatePack <--- not sure why this is being included

This is my package.json, located in .template.config from above:

`{
  "author": "CompanyName",
  "classifications": [],
  "description": "template description",
  "name": "CompanyName Web API",
  "defaultName": "MyApi",
  "identity": "WebApi.CSharp",
  "groupIdentity": "WebApi",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "shortName": "companywebapi",
  "sourceName": "Company.WebApi",
  "guids": [
	"{550200D0-EAAA-4811-8B92-456049A64119}",
	"{4AF4B8D5-3587-40C4-9639-9568582448EE}",
	"{CB49A0FE-8EE2-4F95-A06F-E1472710F286}",
	"{BCFC9351-7D50-4516-B959-36B1770360DC}",
	"{A40A911A-8BA3-4C44-8917-513E0E45FCC8}",
	"{E43D9CC6-96EC-421E-8F0D-1D15587EBEC9}"
	],
  "primaryOutputs": [
    {
      "path": "Company.WebApi.Web\\Company.WebApi.Web.csproj"
    },
    {
      "path": "Company.WebApi.Model\\Company.WebApi.Model.csproj"
    },
    {
      "path": "Company.WebApi.Repository\\Company.WebApi.Repository.csproj"
    },
    {
      "path": "Company.WebApi.Repository.Interface\\Company.WebApi.Repository.Interface.csproj"
    },
    {
      "path": "Company.WebApi.Service\\Company.WebApi.Service.csproj"
    },
    {
      "path": "Company.WebApi.Service.Interface\\Company.WebApi.Service.Interface.csproj"
    }
  ]
}`

Is there anything obvious I'm doing wrong?

**Comment by avrahamcool** [comment]
I think this problem was discussed here - https://github.com/ligershark/sidewafflev2/issues/25

**Comment by hallidev** [comment]
Boy I thought I had read the issues closely, but I must have missed this. I'll give those solutions a shot.

Thanks!

**Comment by hallidev** [comment]
It did. I appreciate the help!
