### ISSUE TITLE
Q: multiple template vsix

### ISSUE THREAD

**Issue by grahamehorner** [ligershark/sidewafflev2#45]
is it possible to create a multiple template VSIX; I have a number of templates each builds and is included in the nuget output, however only one is shown in VS 2019 exp when running the solution; I have confirmed that the output nupkg content folder contains the project templates.  
The template.zip however only has one template.json & template.vstemplate ?

**Comment by sayedihashimi** [comment]
Yes, but the .vstemplate file name needs to be unique. For example template1.vstemplate, template2.vstemplate, etc.
