### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by kyleherzog** [ligershark/sidewafflev2#50]
Are there plans to add support for Visual Studio 2022?

**Comment by sayedihashimi** [comment]
VS2022 now has native support for Template Engine templates, see https://aka.ms/netcore-templates. Please take a look. If you still need this extension in VS2022, please explain your scenario and why the built in support isn’t sufficient.

**Comment by kyleherzog** [comment]
I was able to successfully switch over to the newer template engine.  Thanks for pointing me in that direction.

**Comment by sayedihashimi** [comment]
Thanks for letting me know, that’s great to hear.
