### ISSUE TITLE
Question: about project name for multi-projects

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/sidewafflev2#6]
[Question from youtube](https://www.youtube.com/watch?v=g6az_N95dVM&lc=z22htjb5gpy5sbyru04t1aokgsvomlws1dmezbl1he4qrk0h00410.1503067913976623) 

Thanks, this worked, I am able to create templatepack project and hence an actual project from the template. Nice Work Sayed !!!!! 

I still have two questions, 

1) I have multiple projects within my solution that I wish to make them part of this ProjectTemplate. How can I parameterize the project names for all these projects. 

Example: My VS Solution contains these projects (All are class libraries (.NET Core 2.0)) Abhishek.Component.Entities 
Abhishek.Component.Extensions 
Abhishek.Component.Abstractions 
Abhishek.Component.Tests 

How can I replace "Component" when I create an actual project from a template? 

2) How can I ship this templateProject as a VSIX to my dev team?

**Comment by sayedihashimi** [comment]
>I have multiple projects within my solution that I wish to make them part of this ProjectTemplate. How can I parameterize the project names for all these projects.

In the `template.json` the `sourceName` value will be the text that is replaced. For example in the video the source name is `Demo.Console` ([code](https://github.com/sayedihashimi/sayed-samples/blob/master/dotnet-templates/DemoTemplate/src/.template.config/template.json#L14)). When the projects are created `Demo.Console` will be replaced with the name of the project given in the New Project Dialog.

In your example if you just want `Component` replaced then use `"sourceName": "Component"`.

>How can I ship this templateProject as a VSIX to my dev team?

I would build the project in Release and then share the .vsix file with them. You can do this by putting it on the VS marketplace if you want to make public. If you want to keep it private then put the .vsix on a network share or however you are sharing files today.

**Comment by aagarwal10** [comment]
@sayedihashimi - Thanks a lot for following up. Works great !!!
