### ISSUE TITLE
Add Template Description Field to Template Info Dialog

### ISSUE THREAD

**Issue by shaggygi** [ligershark/sidewafflev2#7]
When creating a template for a project (by right-clicking project > Create Template...), it would be nice to have a Description field provided in the Template Info Dialog while adding other project data.

Currently, a default value of "template description" is added to the template.json file after creating the template.

**Comment by sayedihashimi** [comment]
Good suggestion. We should add it. Let me know if you want to take a crack at sending a PR.

**Comment by shaggygi** [comment]
@sayedihashimi yeah, I can tried to PR it.  gimme some time to review and I'll let you know.  thx

**Comment by sayedihashimi** [comment]
@shaggygi for description I was thinking to add a multi-line text box at the bottom of the WPF dialog.
