### ISSUE TITLE
Changing the icon doesn't seem to work

### ISSUE THREAD

**Issue by jimbobbennett** [ligershark/sidewafflev2#8]
I'm creating a template and want to set the icon, but it doesn't seem to work. 

I've added an icon called project-icon.png to the same folder as the .vstemplate, but it still uses the default icon.

The project in question is here: https://github.com/jimbobbennett/MvvmCross-Templates

**Comment by sayedihashimi** [comment]
It's working for me. If you are testing with F5/CTRL-F5 please try Resetting the Experimental Instance.

**Comment by jimbobbennett** [comment]
Ah - I did not know you could reset the experimental instance. All working, thanks!
